services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app  # Set working directory
    environment:
      - NODE_ENV=development
    command: npm install && npm run start
    stdin_open: true
    tty: true
